include(ExternalProject)

if(NOT EXTERNAL_PROJECT_INSTALL_PREFIX)
  set(EXTERNAL_PROJECT_INSTALL_PREFIX_LOCAL "${CMAKE_CURRENT_BINARY_DIR}/extern-local")
  set(EXTERNAL_PROJECT_INSTALL_PREFIX_GLOBAL "${CMAKE_CURRENT_BINARY_DIR}/extern-global")
endif()

function(ExternalProject_add_local)
  ExternalProject_add(
    ${ARGV}
    CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECT_INSTALL_PREFIX_LOCAL}"
    UPDATE_COMMAND ""
    )

  include_directories(${EXTERNAL_PROJECT_INSTALL_PREFIX_LOCAL}/include)
  link_directories(${EXTERNAL_PROJECT_INSTALL_PREFIX_LOCAL}/lib)
endfunction()

function(ExternalProject_add_global)
  ExternalProject_add(
    ${ARGV}
    CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECT_INSTALL_PREFIX_GLOBAL}"
    UPDATE_COMMAND ""
    )

  include_directories(${EXTERNAL_PROJECT_INSTALL_PREFIX_GLOBAL}/include)
  link_directories(${EXTERNAL_PROJECT_INSTALL_PREFIX_GLOBAL}/lib)

  install(DIRECTORY ${EXTERNAL_PROJECT_INSTALL_PREFIX_GLOBAL}/ DESTINATION ${CMAKE_INSTALL_PREFIX})
endfunction()
